### ISSUE TITLE
UI Issue on Mobile

### ISSUE THREAD

**Issue by zyphermc** [holygrailone/holygrailone#3]
![IMG_20220204_092930](https://user-images.githubusercontent.com/27851243/152458003-82177427-f85b-468f-a453-e74aefe95d65.jpg)

Claim All and Buy HLY button not aligned properly.
Container for stats not stretching to contain whole info.

**Comment by holygrailone** [comment]
Resolved in https://github.com/holygrailone/holygrailone/commit/c43adb7833fa61df33d649518fc2c9f92fdd7637

Will be up in the next few minutes, Thanks!
